version: "3.5"

services:
  build:
    image: contract-builder
    build:
      context: ../..
      dockerfile: ./scripts/docker/Dockerfile
    volumes:
      - ./build:/build:rw
    env_file:
      - .env
    command: "yarn deploy ${NETWORK}"